### ISSUE TITLE
Add Linguist Compatibility?

### ISSUE THREAD

**Issue by bjskistad** [LilCoders/LPMs#4]
If you create a PR to GitHub's Linguist, you could start parsing for LPMs.

**Comment by CosmicWebServices** [comment]
Thanks I am researching now but one of our members prob knows more about this

**Comment by herohamp** [comment]
LPM is just a txt file renamed ;P

**Comment by CosmicWebServices** [comment]
Yeah but thanks for pointing this out @bjskistad

**Comment by bjskistad** [comment]
Yes, it is just a text file, but it's a text file with JavaScript in it, and you could parse for a LPM file and Syntax highlight it.

**Comment by bjskistad** [comment]
And technically, all files are just text files. :P

**Comment by CosmicWebServices** [comment]
Interesting point

**Comment by bjskistad** [comment]
:)

**Comment by CosmicWebServices** [comment]
I will do this tonight

**Comment by CosmicWebServices** [comment]
@bjskistad So it is kind of working but can you make a Pull Request (when you have a chance) or just tell me how to make the javascript highlight in .lpm files? Thanks!

**Comment by bjskistad** [comment]
I honestly wouldn't recommend doing this if you don't get big:  

1. Go to https://github.com/github/linguist
2. Fork the repository.
3. Read https://github.com/github/linguist/blob/master/CONTRIBUTING.md
4. Submit your correct and eligible pull request.

**Comment by CosmicWebServices** [comment]
OK I submitted a request
